### ISSUE TITLE
Problem with Alignment

### ISSUE THREAD

**Issue by JuliApril** [dolanmiu/docx#1144]
Hello, could you please explain, whether it is possible to use Alignment properties online?
Im trying to set Alignment in your jsfiddle example and it doesnt work!
![image](https://user-images.githubusercontent.com/39876731/132583993-1dc151d6-2d05-4142-a682-988711aa3e68.png)

Thanks!

**Comment by dolanmiu** [comment]
Try docx.AlignmentType.CENTER

**Comment by JuliApril** [comment]
> Try docx.AlignmentType.CENTER

It works! Thank you very much!
And is there another way to change font size except heading level property and xml ?

**Comment by anti-the-social** [comment]
@JuliApril I think you'll find these links useful since it represents all properties:

for TextRun: https://docx.js.org/api/interfaces/irunoptions.html
for Paragraph https://docx.js.org/api/interfaces/iparagraphoptions.html
More readable version from the documentation that is a little not full / not always up to date: https://docx.js.org/#/usage/styling-with-js?id=available-options

In your case you are look for size parameter for textRun. It is represented in 1/2 of a point so to get size 13 you put 26

**Comment by anjopater** [comment]
I know it's close but I noted that for codes like this.

```
         new Paragraph({
              text: `text here`,
              alignment: AlignmentType.RIGHT,
              spacing: {
                after: 600
              }
            }),
```
the ` alignment: AlignmentType.RIGHT,` property does not work, only works when you add the `heading` property.

`heading: HeadingLevel.HEADING_2,`

```
         new Paragraph({
              text: `text here`,
              alignment: AlignmentType.RIGHT,
              heading: HeadingLevel.HEADING_2,
              spacing: {
                after: 600
              }
            })
```

I tried with `AlignmentType.END` and also is not working. 

**Note**
I added in the codePen example original code the `docx` prefix
