### ISSUE TITLE
this document contains fields that may refer to other files. Do you want to update the fields in this document?

### ISSUE THREAD

**Issue by KamilZajac** [dolanmiu/docx#1212]
Every time I create a docx file and try to open it, I see a prompt that says "this document contains fields that may refer to other files. Do you want to update the fields in this document?".

In my case, I'm using it in my Angular/Electron app, but for testing, I've created a new file, which is a literal copy of this file:
https://github.com/dolanmiu/docx/blob/master/demo/28-table-of-contents.ts and the same problem is occurring.

I'm using node v16.9.1 and tried this on docx v7.1.1 and v6.0.3, and for Word, I'm using v2109 ( from Microsoft 365 Apps for business )

Is there any solution for this?

**Comment by lemcii** [comment]
Also having this issue.

`updateFields: true` isn't in the TypeScript definitions, guessing this part is missing implementation?

**Comment by devoidfury** [comment]
It is in there, are you on version 7?

**Comment by kevindesousa** [comment]
I have the same problem, how disable this popup ?

**Comment by dylangrandmont** [comment]
Adding this flag when creating the document does not appear to remove this prompt

```ts
new Document({
  ...
  features: {
    updateFields: true,
  }
})
```

**Comment by brycehorman** [comment]
any update on this issue?

**Comment by kevindesousa** [comment]
update ?

**Comment by yousufkalim** [comment]
update?

**Comment by kalda341** [comment]
@anti-the-social This aligns with what I believe to be the case too. I feel like there should be a way to automatically update the fields upon opening the document in Word without the popup, but I haven't been able to find a way.

**Comment by anti-the-social** [comment]
@kalda341 I did try to create TOC via word and then modify dirty="true" to it, it does ask it also on opening. So I have doubts on ability to turn that off...

**Comment by dolanmiu** [comment]
Related issue:

https://github.com/dolanmiu/docx/issues/885

I do not think this is possible because `Pages` as a concept isn't part of OOXML. `docx` has no way of knowing what page what thing is on.
The pages you see in Word is done by rendering the document, then Word inserts it in. It has nothing to do with the word document itself.

The error you see is actually a prompt for Word to generate those numbers based on whats rendered.

### Solution:
Sure, we can approximate the page numbers based on the content, then insert it in ourselves, but it is far from easy (tables, font sizes and widths, line breaks). Essentially creating a renderer at that point.

**Comment by 0x1234567890** [comment]
How to use "updateFields:true" with the patcher?

```
patchDocument(fs.readFileSync("template.docx"), {
    patches: {
        headline: {
            type: PatchType.PARAGRAPH,
            children: [new TextRun("My New Headline")],
        },
		summary: {
            type: PatchType.DOCUMENT,
            children: [ new TableOfContents("summary", {
                    hyperlink: true,
                    headingStyleRange: "1-5",
                })],
        },
    },
}).then((doc) => {
    fs.writeFileSync("output.docx", doc);
});
```
