### ISSUE TITLE
The "LineRuleType.EXACTLY" setting is NOT work correctly

### ISSUE THREAD

**Issue by weiwei3381** [dolanmiu/docx#1773]
My version of docx.js is 7.6.0, when I set config like this
`          paragraph: {
            alignment: AlignmentType.CENTER,
            spacing: { line: 28.9 * 20, lineRule: LineRuleType.EXACTLY },
          }
`
The docx file I got in xml like this:
`
<w:spacing w:line="578" w:lineRule="exactly"/>
`
but the MS word displaying this file is not correct. When I modify the xml file "exactly" to "exact", It display correct. The correct xml code like this
`
<w:spacing w:line="578" w:lineRule="exact"/>
`
I use MS word 2019, I'm not sure whether the problem is caused by MS Word. Thank you for your help.

**Comment by dolanmiu** [comment]
Interesting

From the official documentation, it is `exactly` not `exact`:

http://officeopenxml.com/WPspacing.php

> Specifies how the spacing between lines as specified in the line attribute is calculated.
Note: If the value of the lineRule attribute is atLeast or exactly, then the value of the line attribute is interpreted as 240th of a point. If the value of lineRule is auto, then the value of line is interpreted as 240th of a line.

**Comment by anti-the-social** [comment]
Hello :) 

Not so long time ago noticed that these type of things are related to the difference between these standards:

1. Open Office XML 
2. Office Open XML
3. Open XML

Yet not sure if "Open XML" are same with "Open Office XML" but I definitely know for the past issues we handled we followed the "Office Open XML" which is slightly different from what Word uses. e.g. in this `w:lineRule`

e.g. Word's own Open XML says `exact` 
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.linespacingrulevalues?view=openxml-2.8.1

And here is note for OOXML meaning different formats
<img width="823" alt="image" src="https://user-images.githubusercontent.com/69673750/202384148-06390581-1961-4d38-a845-4df667fb2b96.png">
Source: http://officeopenxml.com/

P.S. if we would use `exact` instead of `exactly` we might have problems with other editors, like libre office or open office. I have not tested that yet.

**Comment by anti-the-social** [comment]
It is a big question for lib what to use...
It could be potentially worth to follow "Open XML" from Word since it has developed further to some degree.
As an example from my recent findings is the "Content control" feature that cannot be found on http://officeopenxml.com/

It has a tag `sdt` which translates to "Block-Level Structured Document Tag". It wraps multiple paragraphs
There is also `sdtContent` which is only for one paragraph.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/69673750/202392039-921ef17a-92fe-455f-a819-5a1c62181fe6.png">
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.sdtblock?view=openxml-2.8.1

**Comment by anti-the-social** [comment]
I'll also leave here related issue from the past: https://github.com/dolanmiu/docx/issues/1277

**Comment by dolanmiu** [comment]
I will add `EXACT` to the list too, so people can pick and choose. I do not want to deprecate anything until a major version update

**Comment by weiwei3381** [comment]
Thank you for your attention, It would be great if relevant settings could be added.
