### ISSUE TITLE
Cells fixed width

### ISSUE THREAD

**Issue by encloinc** [dolanmiu/docx#180]
Is there an option to give table cells a fixed width, that way it wont auto scale with the percentages when the text overflows? Thanks!

**Comment by dolanmiu** [comment]
You can set the table to be fixed width:

```js
table.setFixedWidthLayout();
table.setWidth(WidthType.DXA, 4535);
```

but I am not sure about cell, probably a new feature

**Comment by dolanmiu** [comment]
Correction, it does work:

https://github.com/dolanmiu/docx/issues/94

**Comment by gal664** [comment]
@dolanmiu i'm using your API on node.js, and mostly it's really great.

I do have an issue with the cells width, since i'm new to this it's probably a misunderstanding on my side,
I'm trying to set the width and height for all the cells in a table I'm generating to be the same.

on my perspective it means i have to both take care of the cell width and the text overflow.
I didnt manage to do neither so far and would really appreciate your help!
currently I have this code:
`const table = doc.createTable(10, 6)
 table.setWidth(docx.WidthType.PERCENTAGE, '100%');`

then I'm running a loop creating the cell paragraphs:
    
`let text = new docx.TextRun(string).size(24).font("calibri").bold().rightToLeft()`
`let paragraph = new docx.Paragraph().center()`
`paragraph.addRun("text")`
`let cell = table.getCell(i, j).addContent(paragraph)`

I would appreciate any help from anyone, this is one of the last things left for me to do!

**Comment by dolanmiu** [comment]
Hey

> I'm trying to set the width and height for all the cells in a table I'm generating to be the same.

So by width and height being the same, do you mean make a square cell for each cell?

**Comment by gal664** [comment]
not necessarily a square cell, but what I need is that all of the table's cell will have the same height and the same width.

I just meant to update here - I think I understood what controls the cell's size:

`let paragraph = new docx.Paragraph().center().spacing({before:250, after:250})`

is this the right way to control the size of cells in a table? is there a better method?

other than that I managed to use the API very well and it's been very useful for me.

**Comment by dolanmiu** [comment]
Will be fixed with:

https://github.com/dolanmiu/docx/pull/288
