### ISSUE TITLE
Wrong Table width when preview file & uploading Google Docs

### ISSUE THREAD

**Issue by huynhtansi** [dolanmiu/docx#216]
Hi, dolanmiu. Thank you for awesome library.

I has a problem when creating a full-width table with code:

`
const table = doc.createTable(3, headers.length)
table.setWidth(WidthType.PERCENTAGE, '100%')
`

It works fine when open in Microsoft Word, but wrong width when preview in Google Docs or Finder (I'm using MacOS).

Microsoft Word: 

<img width="799" alt="screen shot 2018-12-07 at 5 12 03 pm" src="https://user-images.githubusercontent.com/16728346/49641656-6344b480-fa43-11e8-85c2-1e282c30f437.png">

Google Docs:

<img width="816" alt="screen shot 2018-12-07 at 4 58 57 pm" src="https://user-images.githubusercontent.com/16728346/49641670-735c9400-fa43-11e8-88c2-5a9c04618611.png">

Finder Preview:

<img width="806" alt="screen shot 2018-12-07 at 5 12 29 pm" src="https://user-images.githubusercontent.com/16728346/49641683-7a83a200-fa43-11e8-8b97-dabf9836887f.png">

**Comment by dolanmiu** [comment]
Yes, Gogole docs, or finder is not supported

Only Microsoft Word so far

If you can figure out how to get the features working in each, that would be amazing

**Comment by carlbolduc** [comment]
I use Tab Stops to work around this, they work perfectly in both Pages and Google Docs.

**Comment by vahid18u** [comment]
Would you please write somewhere in the documentation with **bold** font that this package does not support google docs ? It took more than 2 days for me to find it out and see this issue with table width. Thanks

**Comment by WilliamPeralta** [comment]
@vahid18u if you want you can add the warning on the documentation yourself and open a PR,

**Comment by baloo887** [comment]
> I use Tab Stops to work around this, they work perfectly in both Pages and Google Docs.

Hi @carlbolduc , can you please explain how you use tab stops in your workaround? Everything else is working fine in my document, but tables. If your workaround works, you made my day!!

**Comment by carlbolduc** [comment]
> Hi @carlbolduc , can you please explain how you use tab stops in your workaround? Everything else is working fine in my document, but tables. If your workaround works, you made my day!!

Here is an example, I first create a line like this:
```
const line = this.doc.createParagraph().bullet().maxRightTabStop();
```
I can then add content to it:
```
line.createTextRun('Stuff...');
```
And use tab stops to simulate a table:
```
line.createTextRun('Other stuff').tab();
```

**Comment by krooq** [comment]
@carlbolduc I have tried the tab stops and they don't seem to work in Google docs either.. perhaps the implementation has changed since Novemebr

**Comment by carlbolduc** [comment]
> @carlbolduc I have tried the tab stops and they don't seem to work in Google docs either.. perhaps the implementation has changed since Novemebr

I'm using version 5.0.0-rc4. Anything else after that broke my implementation so I stay on this version.

**Comment by dolanmiu** [comment]
I have found the issue, it is because you need to explicitly specify the widths

Most word processors aren't smart enough to figure out what width you want. Microsoft Word seems to be the exception and figures out the desired result nicely.

Check out this demo on how to specify widths (column widths and cell widths):

https://github.com/dolanmiu/docx/blob/master/demo/4-basic-table.ts

here are the results from different word processors using that demo:

# Word 365:

![Screenshot 2021-03-05 at 03 07 25](https://user-images.githubusercontent.com/2917613/110061958-587f4400-7d60-11eb-8a03-5c88cf6f3002.png)

# Libre Office:
![Screenshot 2021-03-05 at 03 07 41](https://user-images.githubusercontent.com/2917613/110061961-5917da80-7d60-11eb-8d7c-9c333b492289.png)

# Google docs:
![Screenshot 2021-03-05 at 03 07 50](https://user-images.githubusercontent.com/2917613/110061963-59b07100-7d60-11eb-96ba-79ab0b37c3fb.png)

In future, I will consider making `docx` "smarter" so it knows what width the user intends... but that seems to be a challenge in itself.
