### ISSUE TITLE
Right-to-Left two columns document

### ISSUE THREAD

**Issue by nitayke** [dolanmiu/docx#2220]
Hi, is there a way to make a document with 2 columns, that the left column will be after the right one?
(My document is written in hebrew)
I cannot find this property here:
![image](https://github.com/dolanmiu/docx/assets/63166525/efe8fc69-1090-44ae-86f2-ed6bfcbb2671)

**Comment by nitayke** [comment]
I succeed:
![image](https://github.com/dolanmiu/docx/assets/63166525/2ccf4bad-91c9-4aae-80ec-6fd3432dabf6)

**Comment by dolanmiu** [comment]
Nice, glad to hear it

**Comment by aala-h-m** [comment]
Hi,

I am facing a similar issue, tried the suggested approach but it didn't work, might be because my document consists of multiple sections (I can't specify the index of the columns section as the content is being generated dynamically). I also tried setting the textDirection property in the section as follows:

![Image](https://github.com/user-attachments/assets/f5ee1027-3eda-43ac-936a-5cf7cc2704be)

but it rotates the text instead of just making the direction from right to left. Is there another approach that I can follow?
