### ISSUE TITLE
Can't open documents generated with ^8.1.0 in Next.js API route using Packer.toBuffer()

### ISSUE THREAD

**Issue by rbourdon** [dolanmiu/docx#2237]
I use docx in a Next.js application (pages directory) in an api route with Packer.toBuffer(), and after v8.1.0 Word has failed to open the generated document.

Here's a simple reproduction on codesandbox: https://codesandbox.io/p/sandbox/exciting-meadow-k89f6g 

Reverting back to 8.0.4 resolves the issue.

**Comment by Sliffcak** [comment]
Same Issue here.

**Comment by joshkel** [comment]
I've encountered what I believe is the same issue. I have a [Hapi](https://hapi.dev/) backend that started returning unusable values when I upgraded to 8.1.0.

Since it started with 8.1.0, I believe it's the result of the migration to Vite in #2148.

From what I can tell:

The problem arises because the output of `Packet.toBuffer()` isn't a Node.js Buffer. It calls itself a Buffer (e.g., if you call JSON.stringify on it, "Buffer" appears in the output), and it's an instance of Uint8Array (just like a real Node.js Buffer), but it's not an instance of Buffer, so Hapi does not invoke its code path for serving a binary blob. I haven't looked into Next.js, but I'm guessing it's the same root problem.

From inspecting the `build/index.cjs` build of docx, it looks like docx -> jszip -> Buffer is resolving to the [third-party buffer package](https://github.com/feross/buffer) instead of using Node.js's native Buffer support. (In case it helps, my application is using the `build/index.cjs` build of docx.)

**Comment by dolanmiu** [comment]
I upgraded the project from `webpack` to `vite` for better DevX and native ESM support

Yes, this is Vite doing some of it's own optimisations (I am guessing to make it compatiable for web and node etc).

Still looking into it

**Comment by Sliffcak** [comment]
8.2.1 Fixed it for me as well.

**Comment by dolanmiu** [comment]
Excellent, thanks for the testing everyone!
