### ISSUE TITLE
exmaple/31-tables creates table with no cell width

### ISSUE THREAD

**Issue by shyamayadav154** [dolanmiu/docx#2723]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cee17eb7-5c53-40d1-a20f-6b00953c3387">

**Comment by anti-the-social** [comment]
Open it in Word :)

**Comment by shyamayadav154** [comment]
it works is word, but not in google docs or apple pages, does this library doesn't support those two?

**Comment by anti-the-social** [comment]
They are not as smart as Word. Word does re-calculate width values for you in the background.
So if you re-save with Word then width will be fixed and tables openable in other editors.

There is tonns of issues opened concerning that in the past.
e.g. https://github.com/dolanmiu/docx/issues/1947 https://github.com/dolanmiu/docx/issues/2712

To my knowledge such recalculation aren't planned to be as a part of docxjs library due to technical reasons.

To make tables work in every editor you have to sent absolute widths.
