### ISSUE TITLE
Images are inserted skewed

### ISSUE THREAD

**Issue by acgrama** [dolanmiu/docx#283]
Images are inserted with a skew that scaling doesn't _quite_ fix.

For example, I am trying to insert this original image:
![google](https://user-images.githubusercontent.com/1415729/53880404-33408980-4011-11e9-8eda-396b0ad8958d.png)

It is inserted like this (sorry for the German UI, but you can see the original rectangular image of 4,87 x 14,39 cm has been skewed to a square of 2,65 cm):
![auto_insert](https://user-images.githubusercontent.com/1415729/53880440-44899600-4011-11e9-8591-630f6bccb713.JPG)

If I scale it, for instance **scale(3, 1)**, the image is still shown skewed, but you can see from the image dialog that the size has been correctly scaled:
![scaled](https://user-images.githubusercontent.com/1415729/53882399-8701a180-4016-11e9-9fe8-b01f1c1beff4.JPG)

At this point, if I click OK in this dialog, the setting kicks in and the image will be shown scaled correctly.

**Comment by dolanmiu** [comment]
Yes this is expected and deliberate behavoir

all images are default 100 x 100

it is up to you to specify the dimensions

it is incredibly difficult to deduce the dimensions of an image based on raw buffer data

until that is resolved, it will be 100 x 100 by default

**Comment by acgrama** [comment]
Thanks for the explanation!

**Comment by ankushgarg1998** [comment]
> Yes this is expected and deliberate behavoir
> 
> all images are default 100 x 100
> 
> it is up to you to specify the dimensions
> 
> it is incredibly difficult to deduce the dimensions of an image based on raw buffer data
> 
> until that is resolved, it will be 100 x 100 by default

How to specify image dimensions?

**Comment by rizedr** [comment]
> all images are default 100 x 100

What is the unit @dolanmiu ?

**Comment by dolanmiu** [comment]
Units are DXA:

https://stackoverflow.com/questions/14360183/default-wordml-unit-measurement-pixel-or-point-or-inches

**Comment by rizedr** [comment]
Amazing thanks @dolanmiu, going to add this in the docs.

**Comment by rizedr** [comment]
@dolanmiu the units for `IMediaTransformation` width & height properties? Doesn't seem to be DXA

For a `width` value of 648 for the property, it produces an image with the 16.88cm (which is around 9570 DXA).

**Comment by dolanmiu** [comment]
Perhaps it is EMU?

https://social.msdn.microsoft.com/Forums/office/en-US/19245f64-eae4-4d89-8084-4240c866cf7c/how-to-set-images-width-and-height-when-insert-an-image-to-word-

**Comment by dolma** [comment]
> What is the unit @dolanmiu ?

> From my tests, it looks that a value of IMediaTransformation.width = 100 corresponds to 2.65cm in the output doc. (don't understand how that works tho.)

@dolanmiu @rizedr I've investigated a bit and looked like it's converted with a ratio of about `3.78` which seems to correspond to a conversion from pixels to mm (see [this page](https://www.unitconverters.net/typography/pixel-y-to-millimeter.htm)). The precise ratio is actually `3.7795275591`. Hence why the default `100` value (i.e. 100 pixels) outputs about 2.65cm (exactly 26.46mm).

I'm using this workaround function to hide that conversion, could be worth adding it to the repo:

`const convertMillimetersToPixels = (millimeters: number) => millimeters * 3.7795275591;`

**Note 1**: I also found that I need the following conversion function for points -> twip. It's useful typically for things like line spacing rules that tend to be displayed in points in the Word UI.

`const convertPointsToTwip = (points: number) => points * 20;`

**Note 2**: Generally I've been finding it very hard to find any information about units in the docs for certain parts of the api. Could be worth at the very least explicitly mentioning what unit is being used for each size-type property and give corresponding conversion function(s) for each. Would be even better if we could use `PositiveUniversalMeasure` values for all size-type properties and abstract the conversion process within the api rather than have the user figure out the right unit for each property. For example, I could set an image width to `'100mm'` and it would convert that to `377.95`, or I could set it to `'10cm'` or `'3.937in'`, etc. and still get the right pixel width value of `377.95`. It would also make the api a bit more consistent and predictable for the users.

**Comment by strblr** [comment]
@dolma You saved me hours, thanks

**Comment by DanielGibbsNZ** [comment]
Just to add some context to @dolma's number of 3.7795275591 above: this is the ratio between millimeters and pixels at 96 DPI. The same result can be achieved by converting from millimeters to inches and then converting to pixels at 96 DPI:

```
const inches = mm / 25.4
const pixels = inches * 96
```
