### ISSUE TITLE
table support for mac pages

### ISSUE THREAD

**Issue by Willworkgogogo** [dolanmiu/docx#294]
In addition to ms word, MAC pages is a common scenario, and the setting of table width is invalid under MAC pages. I think it is necessary to make this compatibility first. Thanks for your effort

**Comment by jiangyongyuan** [comment]
same problem , I had try many times , but the setWidth not work

**Comment by rickgrana** [comment]
Try this:

`new Table({
                rows: [your rows],

                width: {
                    size: 100,
                    type: WidthType.PERCENTAGE,
                },
                
                
            })`

**Comment by avevlad** [comment]
@rickgrana did not work 

![image](https://user-images.githubusercontent.com/2889662/79326666-eae5e180-7f1b-11ea-9f6b-5d5b7d6c1f4a.png)

**Comment by rickgrana** [comment]
Really not working. Only way is to set fixed columnWidths

**Comment by dolanmiu** [comment]
I have found the issue, it is because you need to explicitly specify the widths

Most word processors aren't smart enough to figure out what width you want. Microsoft Word seems to be the exception and figures out the desired result nicely.

Check out this demo on how to specify widths (column widths and cell widths):

https://github.com/dolanmiu/docx/blob/master/demo/4-basic-table.ts

here are the results from different word processors using that demo:

# Mac Pages

![Screenshot 2021-03-05 at 03 25 06](https://user-images.githubusercontent.com/2917613/110063108-6fbf3100-7d62-11eb-8448-a72956464eee.png)

# Word 365:

![Screenshot 2021-03-05 at 03 07 25](https://user-images.githubusercontent.com/2917613/110061958-587f4400-7d60-11eb-8a03-5c88cf6f3002.png)

# Libre Office:
![Screenshot 2021-03-05 at 03 07 41](https://user-images.githubusercontent.com/2917613/110061961-5917da80-7d60-11eb-8d7c-9c333b492289.png)

# Google docs:
![Screenshot 2021-03-05 at 03 07 50](https://user-images.githubusercontent.com/2917613/110061963-59b07100-7d60-11eb-96ba-79ab0b37c3fb.png)

In future, I will consider making `docx` "smarter" so it knows what width the user intends... but that seems to be a challenge in itself.
