### ISSUE TITLE
setHorizontalAlign - TableCellProperties

### ISSUE THREAD

**Issue by supervanya** [dolanmiu/docx#335]
Are there any plans of implementing `setHorizontalAlign` for cells? If not, would it be helpful if I do a PR with the method? I think it would be similar to #146.

**Comment by dolanmiu** [comment]
Yes it would be great if you can make a PR

I am currently re-designing the `Paragraph` and adding shading/highlights, so im busy at the moment

**Comment by supervanya** [comment]
@dolanmiu After looking into the documentation, it looks like word doesn't have a way to align cells horizontally, what it does instead is paragraph justification using `w:jc w:val='...'`
http://officeopenxml.com/WPalignment.php

Is there any way to access the paragraph(s) in the cell of the table? If not, I am not sure it is possible to have a `setHorizontalAlign` method.

**Comment by dolanmiu** [comment]
you should create the paragraph, make it perfect, then add it to the cell last

> Is there a way to do so?

currently? nope not yet

I am still thinking of the best wway to do it, and yes i did some research too, it seems like only vertical alignment is supported, i cant find anything to do with horizontal alignment:

http://officeopenxml.com/WPtableCellProperties-verticalAlignment.php

**Comment by dolanmiu** [comment]
This is a non-issue

I just tried to do it in Word, and reverse engineer how Microsoft Word does it.

I have found that it simply makes the paragraph horizontally aligned

I do not think there is such thing as horizontal alignment for a table

Feel free to prove me wrong otherwise

Check the screenshot

![Screen Shot 2019-11-24 at 02 49 12](https://user-images.githubusercontent.com/2917613/69488724-2eed2280-0e65-11ea-8513-d735f3bf3b24.png)

**Comment by supervanya** [comment]
You are right! I have discovered the same behavior on my own. Thanks for looking into it thought!
