### ISSUE TITLE
Error with docx and browserify

### ISSUE THREAD

**Issue by quentin2k29** [dolanmiu/docx#35]
Hi, 
I'm working on a project and I use Angularjs with Cordova. So I tried to put docx in a bundle with browserify but I got an error when I execute the code.

Everything is fine when browserify create the bundle but I get an error when the app use the bundle :

`TypeError: fs$ReadStream is undefined line 14056`

I checked the code and the variable legstream is undefined so I think the error comes from the legacy(fs) but I don't know why.

 ```
 if (process.version.substr(0, 4) === 'v0.8') {
    var legStreams = legacy(fs)
    ReadStream = legStreams.ReadStream
    WriteStream = legStreams.WriteStream
  }

 var fs$ReadStream = fs.ReadStream
 console.log(legStreams);
 ReadStream.prototype = Object.create(fs$ReadStream.prototype)
 ReadStream.prototype.open = ReadStream$open

```
If someone already had this problem or used this module with browserify and can help me, thanks :)

**Comment by dolanmiu** [comment]
Unfortunately, this library does not work with browser based environment. Aka no Angular, no react etc. This is because it internally uses `archiver` which uses `fs`.

`fs` only exists in node.js, hence why you are getting this error!

**Comment by quentin2k29** [comment]
Thanks for you quick answer ! Do you know an other solution for creating and saving a .docx file using Angular and Cordova ?

**Comment by dolanmiu** [comment]
Not that I know of, the problem is, a .docx file is actually a .zip file, try it! Rename a .docx to .zip, right click > extract all 😂😂

The problem is... all zipping functionality is not supported by browsers for JavaScript. Probably for security reasons

If you find a way, let me know; and I'll add it!

**Comment by dolanmiu** [comment]
Closing as `docx` does not support browser environment due to it accessing file system:

https://github.com/archiverjs/node-archiver/issues/224

**Comment by kharmonycentral** [comment]
Was just reading through some issues and found this discussion. Since the latest release, I see now in the documentation that it mentions running docx in the browser environment (for example in the Packer text: "It works in both a node and browser environment (Angular etc)").

Can you (@dolanmiu) provide a little more info or include something in the docs for how to get it running in the browser environments (such as AngularJS)? I tried including the docx files in my scripts and then referencing it in my controllers, but I couldn't get it to work. Thank you again for your time!

**Comment by dolanmiu** [comment]
Yup! As of `4.0.0` `docx` works on the browser 😄 

https://codepen.io/anon/pen/dqoVgQ
https://jsfiddle.net/3xhezb5w/2

**Comment by Philipotieno** [comment]
@dolanmiu how can I use it with react

**Comment by dolanmiu** [comment]
Seems like it does not work with React at the moment due to ES5 issues
