### ISSUE TITLE
How to insert raw OOXML into document.xml ?

### ISSUE THREAD

**Issue by zahrafali** [dolanmiu/docx#365]
I have equations in OMML format, is there a way, where I can create a function inside document.ts or paragraph.ts so that I can add this code to the document structure

sample OMML code that i'm using - ```<?xml version="1.0"?>
<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:mml="http://www.w3.org/1998/Math/MathML"><m:f><m:fPr><m:type m:val="bar"/></m:fPr><m:num><m:r><m:t>1</m:t></m:r></m:num><m:den><m:r><m:t>2</m:t></m:r></m:den></m:f></m:oMath>```

**Comment by dolanmiu** [comment]
I think this would be out of scope for this library I am afraid

There was someone who made a PR into this functionality, but I haven't tested it, and may consider removing it

**Comment by efx** [comment]
@zahrafali I agree with @dolanmiu because arbitrary XML could break the document in unknown ways. We should probably close this issue.
But you could post process the document to experiment adding custom XML. In my case I have had to replace text in the underlying document and found you can do some modifications to the `word/document.xml` quite easily.
If you follow steps 5-6 in https://docx.js.org/#/usage/styling-with-xml it explains how to see the XML files that make up a Word document.

**Comment by efx** [comment]
If you need to add equations it looks like dolan's work here could help: https://github.com/dolanmiu/docx/pull/381
