### ISSUE TITLE
SubList

### ISSUE THREAD

**Issue by KennyBarraud** [dolanmiu/docx#37]
Hi !
It's me again.
I'm actually triying to make a list with a sublist like this : 

```
1.
   1.1
   1.2
2.
...
```

In order to do that, I'm basing my work on your exemple : 
```
const numbering = new docx.Numbering();
const numberedAbstract = numbering.createAbstractNumbering();
const numberedAbstractLevel2 = numbering.createAbstractNumbering();
numberedAbstract.createLevel(0, "number", "%1.", "left");
numberedAbstractLevel2.createLevel(1, "number", "%1.2", "left");

const levelNumbering1 = numbering.createConcreteNumbering(numberedAbstract);
const levelNumbering2 = numbering.createConcreteNumbering(numberedAbstractLevel2);
doc.createParagraph('Test heading2 with double red underline').setNumbering(levelNumbering1, 0).heading1();

for(var opt = 1; opt < 4; opt++) {
    doc.createParagraph('Option ' + opt).setNumbering(levelNumbering2, 1);
}

doc.createParagraph('Test heading2 with double red underline').setNumbering(levelNumbering1, 0).heading1();
```

But this is the result I get : 
```
1.
   0.2
   0.2
   0.2
2.
...
```
Where is my mistake ? Could you explain to me how the lists are working ?
Thanks :3

**Comment by dolanmiu** [comment]
Hey again,

There is actually a bug I found while trying to investigate your issue. Fixed in `2.1.2` so please update.

I have made a `demo3.js` in the project which will do as you wish: 

https://github.com/dolanmiu/docx/blob/master/demo/demo3.js

<img width="806" alt="screen shot 2017-07-29 at 01 28 23" src="https://user-images.githubusercontent.com/2917613/28740498-4e5317b0-73fd-11e7-903f-5ba375d81b16.png">

**Comment by KennyBarraud** [comment]
Thanks.
Is it possible when you have a sublist to get the number of the parent list; like 1.1, 1.2, etc ?

**Comment by dolanmiu** [comment]
This is possible yes

Please check out demo:

https://github.com/dolanmiu/docx/blob/master/demo/64-complex-numbering-text.ts
