### ISSUE TITLE
Bulletpoints-as numbers

### ISSUE THREAD

**Issue by alexaalex70** [dolanmiu/docx#434]
Bulletpoints as numbers are supported ?

**Comment by jamesmontalvo3** [comment]
I'm not sure if there is a way to easily use standard bullet points. @dolanmiu may be able to answer that. But this is how I do custom bullet point characters to generate checkboxes for each item:

```javascript
const level = abstract.createLevel(
	0,
	'decimal', // this doesn't really matter since below you're defining everything to be a "q"
	'q', // this will make every "bullet" a letter "q", which in Wingdings font is a checkbox
	'left'
);
level.addRunProperty(new docx.RunFonts('Wingdings'));
```

@dolanmiu is in the process of making everything (or at least most things) use a declarative style, so rather than the `level.addRunProperty()` method used here you'll likely have to do something slightly different before version 5.0.0 is officially released.

**Comment by dolanmiu** [comment]
Yes @jamesmontalvo3 is correct, using `decimal` will create numbered bullet points

The createLevel method is now different though due to the API changes

Refer to the demo for more details

https://github.com/dolanmiu/docx/blob/master/demo/29-numbered-lists.ts
