### ISSUE TITLE
Example page is not rendering blank page

### ISSUE THREAD

**Issue by shajanjp** [dolanmiu/docx#445]
Page at https://docx.js.org/#/examples is rendering nothing except the side bar layout.

**Comment by dolanmiu** [comment]
I am planning to remove this page and add examples in the respective documentation sections, rather than grouping ALL the examples one giant "examples" page.

Now theres nearly 50 examples in https://github.com/dolanmiu/docx/tree/master/demo

That `/demo` folder is hard enough to use already, I think having a page dedicated to examples could potentially be worse

Hope this helps!
