### ISSUE TITLE
Attempting to write a heading (in browser) gives error

### ISSUE THREAD

**Issue by daldred** [dolanmiu/docx#485]
I would like to use docx.js to write content from a PHP-based website into a Word document (to help a group administrator create a print newsletter using info already entered onto their website).

I'm trying to get started by writing a heading and a bit of text to the document using this code (adapted from the example of using docx.js in the browser, and the example of how to write  heading in the docs:

```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/docx@4.0.0/build/index.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>
</head>

<body>

    <h1>DOCX browser Word document generation</h1>
    <button type="button" onclick="generate()">Click to generate new document</button>

    <script>
        function generate() {
            const doc = new Document();
            const paragraph1 = new Paragraph({
                  text: "This is the heading",
                  heading: HeadingLevel.HEADING_1
            });*/
            const paragraph2 = new Paragraph({
                  text: "This is the text"
            });
            doc.addParagraph(paragraph1);
            doc.addParagraph(paragraph2);
            const packer = new Packer();
            packer.toBlob(doc).then(blob => {
              console.log(blob);
              saveAs(blob, "example.docx");
              console.log("Document created successfully");
            });
        }
    </script>
</body>
</html>
```
This produces an error  "Uncaught ReferenceError: HeadingLevel is not defined"

**Comment by wcqrnj** [comment]
Hello @daldred,

I think the main problem is that you use docx.js version 4.0.0:
`<script src="https://unpkg.com/docx@4.0.0/build/index.js"></script>`

At version 5.0.0-rc5, there was a major change: docx.js started to use declarative programing style, and the transition is still going on.

You can check it in the releases:
https://github.com/dolanmiu/docx/releases

The problem is that many examples use the old style, some of them uses both the old and new style and some of them only the new style. We need to find out, which style we should use actually.
(@dolanmiu does a great job, and we can use declarative style almost everywhere)

You should use the latest version to be able to use declarative style:
> https://unpkg.com/docx@5.0.0-rc7/build/index.js

The other thing is that now you do not need to declare packer, because it is static.

You can find a working version below:
```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/docx@5.0.0-rc7/build/index.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>
</head>

<body>

    <h1>DOCX browser Word document generation</h1>
    <button type="button" onclick="generate()">Click to generate new document</button>

    <script>
        function generate() {
            const doc = new Document();
			
            const paragraph1 = new Paragraph({
                  text: "This is the heading",
                  heading: HeadingLevel.HEADING_1,
            });
			
            const paragraph2 = new Paragraph({
                  text: "This is the text",
            });
			
			doc.addSection({
				children: [
					paragraph1,
					paragraph2,
				],
			});
			
            Packer.toBlob(doc).then(blob => {
              console.log(blob);
              saveAs(blob, "example.docx");
              console.log("Document created successfully");
            });
        }
    </script>
</body>
</html>
```

I hope you got the answer you were looking for.

Cheers,
He-Wolf
