### ISSUE TITLE
createImage and addImage doesn't work on frontend with ReactJS.

### ISSUE THREAD

**Issue by zqlimy17** [dolanmiu/docx#520]
How to add an image through the frontend? I posted the full question here: 
https://stackoverflow.com/questions/60829285/how-to-add-images-with-npm-docx-package-to-word-document

Summary: 
doc.createImage is not a function
Media.addImage takes only blank images

**Comment by ccocker** [comment]
I have the same issue in an angular app, the issue is that you can't use file-system in angular or react app, so the readFileSync won't work.  I think this is because we are probably using typescript and file-system is written in plan js.  

I have not found the solution yet but will post hear when i do find it, i think the answer will be to use an alternative to file-system

**Comment by jjkahrs** [comment]
I've got the same issue. I've tried: 
`const image = Media.addImage(doc, Buffer.from(data,"base64"));`

I can see in the document object that it's being added there. But when I unzip the generated .docx file and look at document.xml, there is no reference to the image. So far I've been unable to find a work around.

**Comment by dolanmiu** [comment]
Here is an example of docx with images in React (base64 and with request):

https://stackblitz.com/edit/react-ts-qdqu7z
