### ISSUE TITLE
OpenOffice doesn't render tables generated with Docx

### ISSUE THREAD

**Issue by marcohamersma** [dolanmiu/docx#556]
Heya,
Our app is creating a document with a table in it, but for some reason the table isn't being recognised in OpenOffice (latest version). The document works fine in Microsoft Word, Apple Pages, and Libreoffice.

Code example + sandbox here: https://codesandbox.io/s/nostalgic-butterfly-nkwbe?file=/src/index.ts

I can't imagine that libreoffice doesn't support tables, so is there anything I'm doing wrong while creating this table, or is did I stumble upon a bug in the library?

![image](https://user-images.githubusercontent.com/577144/86014041-bdd3a600-ba17-11ea-8bec-fc6d388d7c3b.png)

**Comment by yerlantemir** [comment]
the same problem ...

**Comment by dolanmiu** [comment]
I have found the issue, it is because you need to explicitly specify the widths

Most word processors aren't smart enough to figure out what width you want. Microsoft Word seems to be the exception and figures out the desired result nicely.

Check out this demo on how to specify widths (column widths and cell widths):

https://github.com/dolanmiu/docx/blob/master/demo/4-basic-table.ts

here are the results from different word processors using that demo:

# Open Office

![Screenshot 2021-03-05 at 03 21 23](https://user-images.githubusercontent.com/2917613/110062880-ff181480-7d61-11eb-8814-62cf89497282.png)

# Word 365:

![Screenshot 2021-03-05 at 03 07 25](https://user-images.githubusercontent.com/2917613/110061958-587f4400-7d60-11eb-8a03-5c88cf6f3002.png)

# Libre Office:
![Screenshot 2021-03-05 at 03 07 41](https://user-images.githubusercontent.com/2917613/110061961-5917da80-7d60-11eb-8d7c-9c333b492289.png)

# Google docs:
![Screenshot 2021-03-05 at 03 07 50](https://user-images.githubusercontent.com/2917613/110061963-59b07100-7d60-11eb-96ba-79ab0b37c3fb.png)

In future, I will consider making `docx` "smarter" so it knows what width the user intends... but that seems to be a challenge in itself.
